### PR TITLE
Various codelist updates

### PR DESCRIPTION
**Pull request by inglesp**

### CODE REVIEW

**Comment by annaschultze** [comment]
@inglesp this looks good to me, can you remind me what the change was in the latest version - was it the update to the HIV codes?

**Comment by CarolineMorton** [comment]
No this was changing the titles of immunosuppresion to immunosuppression. You need to run `cohortextractor update_codelists` and then add to repo, before it passes tests. happy to this for you if helpful.

**Comment by annaschultze** [comment]
@inglesp that link doesn't work for me, sorry. Can you post it to me on slack?

**Comment by annaschultze** [comment]
For reference, decided with @inglesp to update the version to the latest one existing. This one has PK281 (Congenital absence of thymus) added as a code.

**Pull request merged**
